### ISSUE TITLE
淘宝被下单

### ISSUE THREAD

**Issue by samhzx** [xuan32546/IOS13-SimulateTouch#11]
安装插件之后，无缘无故就自动在淘宝店<<亿阁祺舰店>>给我下单了一笔，还直接支付了。。

**Comment by xuan32546** [comment]
?
我知道你支付密码还能操控你淘宝的话，我会只下一单？
别逗了

**Comment by samhzx** [comment]
主要是，今天安装了这个插件之后，过了几分钟就出现了一笔订单，淘宝设置的免密支付。
