### ISSUE TITLE
Tweak seems to be deprecated on the repo

### ISSUE THREAD

**Issue by ChaosNicro** [xuan32546/IOS13-SimulateTouch#13]
Adding the Repository from the README.md, the only available Package is ZJXTouchSimulation-old.
Since this appears to be a deprecated version, I was wondering whether one could already get an updated one.
No pressure though, if you don't have time to work on it right now and this is intentional. ^_^

**Comment by yuanlizhanshi** [comment]
https://github.com/xuan32546/IOS13-SimulateTouch

**Comment by xuan32546** [comment]
Fixed:)
