### ISSUE TITLE
支持iOS 设备自身模拟点击吗？不需要电脑或其他iOS设备

### ISSUE THREAD

**Issue by sdutlyb** [xuan32546/IOS13-SimulateTouch#16]
支持iOS 设备自身模拟点击吗？不需要电脑或其他iOS设备
在越狱的iphone上运行一个永久后台的APP，去发起点击指令，在另一个第三方APP中进行点按屏幕

**Comment by xuan32546** [comment]
Yes, we support touch simulation on local machine. You can use socket to control your device. For example, you can install python on your iOS devices. Also, objective-c and swift also supports socket.
