### ISSUE TITLE
 'system' is unavailable: not available on iOS

### ISSUE THREAD

**Issue by cocoajin** [xuan32546/IOS13-SimulateTouch#18]
你好，

我编译zxtouch-binary时，提示 system没有，
请问您是如何编译通过，并使用system执行系统命令的。

谢谢

**Comment by xuan32546** [comment]
The compiler will provide you some information about line number of a file that prevents you from compiling zxtouch with system() command. Just comment out the line of the file.

**Comment by cocoajin** [comment]
@xuan32546 
Thank you very much for your reply

**Comment by Yiiff** [comment]
> @xuan32546 Thank you very much for your reply

Hi，请问你那边是如何解决的这个问题啊？修改编译器么？
