### ISSUE TITLE
[Feature Request] Functionality similar to Ankulua's Record and Play

### ISSUE THREAD

**Issue by buitim** [xuan32546/IOS13-SimulateTouch#28]
Hi there!

I really appreciate the work you're putting into this! This might be asking for much, but I'm just wondering how hard it would be to add functionality similar to [Ankulua's Snap and Play](https://ankulua.boards.net/thread/326/general-script-most-games-snap)? I believe you have something close with the upcoming OCR support and pixel color picker. 

What Ankulua's Snap and Play does, if you aren't familiar with it, is records where the user taps and sets a search boundary around that area so if a specific button comes up, the script will just tap the button (as opposed to just repeating predefined touches over and over again). 

If something like this is already in the works, if this isn't going to be implemented, or if I'm just dumb and am missing something that already exists, please feel free to just close this issue.

Thanks again for all the work on this!

**Comment by xuan32546** [comment]
Hi buitim,
Thanks for the suggestion. This is a good suggestion. It is a little bit hard. I will add this feature, but after I finished my main updates on ZXTouch.

**Comment by buitim** [comment]
> Hi buitim,
> 
> Thanks for the suggestion. This is a good suggestion. It is a little bit hard. I will add this feature, but after I finished my main updates on ZXTouch.

No problem. It was just a suggestion 😁. Thanks for this project and keep up the awesome work!
