### ISSUE TITLE
Is zxtouchb binary in usr/bin intended for scripts launching?

### ISSUE THREAD

**Issue by allyalla** [xuan32546/IOS13-SimulateTouch#29]
Hi, Is zxtouchb intended for scripts launching? If yes - what is it's correct syntax then? It outputs only some unapplicable for building guesses by any member of the human race string "zxtouchb[13059:285633] com.zjx.zxtouchb: usage: zxtouchd [parameter] [...]" like help or a suggestion ... Come on!!! That helps not much! What the hell is the mentioned zxtouchD [parameter] then? :) There is no such binary file! Only the zxtouchB exists. Can you provide any working exemple of how to launch zxtouch's script from CLI please? As Steevie's dream's phone system provides no launch shortcuts... Hand-face ... Tge Activator's triggers will not allow to even touch a screen if will be used too many of them (because that all stpd swipes over already occupied by stpd iOS's swipes instead of the compact hotspots usagefor instance). Thats why i asking of the corect syntax of CLI launch script command.
Rgrds!

**Comment by allyalla** [comment]
in other words - using zxtouch aap's binary applet - ie zxtouchb, how to send using an iOS terminal (or sh script):
- OR zxtouchb - play script N 228 ;
-  OR zxtouchb - touch screen at X, Y.
- It is simple but important question, and it is NOT clear.

**Comment by xuan32546** [comment]
Thanks for the issue submission.

Unfortunately, zxtouchb is not currently opened to public now. It will be opened to the public soon. And users of zxtouch can perform touch by zxtouchb in command lines.
