### ISSUE TITLE
Odyssey越狱下无反应

### ISSUE THREAD

**Issue by kj54321** [xuan32546/IOS13-SimulateTouch#3]
iPhone 8P 13.3

uname -a
Darwin Phone 19.2.0 Darwin Kernel Version 19.2.0: Mon Nov  4 17:47:00 PST 2019; root:xnu-6153.60.66~39/RELEASE_ARM64_T8015 iPhone10,2 arm64 D21AP Darwin

dpkg -s com.zjx.pccontrol
Package: com.zjx.pccontrol
Status: install ok installed
Section: Tweaks
Installed-Size: 160
Maintainer: Jason Z
Architecture: iphoneos-arm
Version: 0.0.1-233+debug
Depends: mobilesubstrate, firmware (>= 12.0)
Description: iOS touch simulation library
Name: pccontrol
Author: Jason Z

照文档安装驱动包，但运行代码后无反应，也无任何报错。
推测是Odyssey 基础包被换成了libhooker，不兼容原MobileSubstrate.
望能适配，谢谢.

**Comment by brook11222** [comment]
> iPhone 8P 13.3
> 
> uname -a
> Darwin Phone 19.2.0 Darwin Kernel Version 19.2.0: Mon Nov 4 17:47:00 PST 2019; root:xnu-6153.60.66~39/RELEASE_ARM64_T8015 iPhone10,2 arm64 D21AP Darwin
> 
> dpkg -s com.zjx.pccontrol
> Package: com.zjx.pccontrol
> Status: install ok installed
> Section: Tweaks
> Installed-Size: 160
> Maintainer: Jason Z
> Architecture: iphoneos-arm
> Version: 0.0.1-233+debug
> Depends: mobilesubstrate, firmware (>= 12.0)
> Description: iOS touch simulation library
> Name: pccontrol
> Author: Jason Z
> 
> 照文档安装驱动包，但运行代码后无反应，也无任何报错。
> 推测是Odyssey 基础包被换成了libhooker，不兼容原MobileSubstrate.
> 望能适配，谢谢.

**Comment by kj54321** [comment]
教程太少了，自行摸索后问题已解决：

1. 需安装隐藏包, slieo源内没展示...
```
apt install com.zjx.iosjianshubao
...
killall SpringBoard
```
2. 重签dylib，否则报错

```
-iPhone:~ root# python3 touch.py 
dyld: Library not loaded: /usr/local/lib/libintl.8.dylib
  Referenced from: /usr/local/bin/python3
  Reason: no suitable image found.  Did find:
	**/usr/lib/libintl.8.dylib: code signature invalid for '/usr/lib/libintl.8.dylib'**

Abort trap

codesign -f -s "your id" libintl.8.dylib
```
