### ISSUE TITLE
Still crash on iOS 13.6.1

### ISSUE THREAD

**Issue by winest** [xuan32546/IOS13-SimulateTouch#33]
Similar issue of https://github.com/xuan32546/IOS13-SimulateTouch/issues/25
No problem on 0.0.6 but has problem since 0.0.6u1

Using 0.0.7u2 still crash.

Dump is attached at the bottom of https://github.com/xuan32546/IOS13-SimulateTouch/issues/25

**Comment by xuan32546** [comment]
It should work. 0.0.7-6 is the latest version. Give it a try!

**Comment by winest** [comment]
Tested on 0.0.7-6, seem crash in another place now.
For old version, it will crash immediately after respring.
For 0.0.7-6, it will crash randomly after playing game for a while. (less than 3 minutes)

Latest log:
[Log.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5975373/Log.txt)
[Log2.txt](https://github.com/xuan32546/IOS13-SimulateTouch/files/5975374/Log2.txt)

**Comment by xuan32546** [comment]
There must be some conflicts with zxtouch and the tweaks you installed

**Comment by winest** [comment]
solved after reinstall the whole zxtouch and touch simulation driver. now itworks correctly with 0.0.7u6, thanks
