### ISSUE TITLE
OCR has mem leaks

### ISSUE THREAD

**Issue by edwardair** [xuan32546/IOS13-SimulateTouch#39]
After use the ORC about 10-25 times on iPhoneX, SpringBoard crash:
 
`Mar 27 15:38:50 iPhoneX kernel[0] <Notice>: EXC_RESOURCE -> SpringBoard[5661] exceeded mem limit: ActiveSoft 332 MB (non-fatal)`

**Comment by xuan32546** [comment]
Thanks for this bug report. OCR does have this problem, I will fix that soon.

**Comment by xuan32546** [comment]
fixed
