### ISSUE TITLE
编译环境

### ISSUE THREAD

**Issue by xiao-Up** [xuan32546/IOS13-SimulateTouch#43]
您好，我是一个新手，想自己在上边做一些拓展性的功能，但是我在xcode上编译生成的应用跟您发布的不一样，想请问下要安装啥工具才能编译生成应用。万分感激🙏。

**Comment by rise-worlds** [comment]
为什么关闭了啊？折腾几天了也没编译过。。。

**Comment by xiao-Up** [comment]
搞不会就关闭了
