### ISSUE TITLE
`IndexError` when no strings present in OCR

### ISSUE THREAD

**Issue by kasnder** [xuan32546/IOS13-SimulateTouch#65]
Running `device.ocr((0,100,100,100))` sometimes gives an error (below). This seems to happen when the OCR is successful, but there are no strings present.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/zxtouch/client.py", line 374, in ocr
    temp_dict = {"text": single_string_info[0], "x": single_string_info[1], "y": single_string_info[2],
IndexError: list index out of range
```

**Comment by kasnder** [comment]
I've proposed a PR to fix this.

**Comment by xuan32546-pitt** [comment]
Merged 😊 Thanks

From: Konrad Kollnig ***@***.***>
Reply-To: xuan32546/IOS13-SimulateTouch ***@***.***>
Date: Saturday, January 29, 2022 at 9:47 AM
To: xuan32546/IOS13-SimulateTouch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [xuan32546/IOS13-SimulateTouch] `IndexError` when no strings present in OCR (Issue #65)


I've proposed a PR to fix this.

—
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fxuan32546%2FIOS13-SimulateTouch%2Fissues%2F65%23issuecomment-1024925105&data=04%7C01%7Cjiz176%40pitt.edu%7C7b1494bf977345afb91c08d9e3364ce2%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637790644626105490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=q9HsuMvd0Y7WADpCy2gaTjEn5qUyMVLEVnstf17XM8w%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANJYEL6MHRYCXHQES2XZGLDUYP4YZANCNFSM5NC7GC4A&data=04%7C01%7Cjiz176%40pitt.edu%7C7b1494bf977345afb91c08d9e3364ce2%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637790644626105490%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=iH6lUbJGTgfJLmzu1HQCmJI1W5KElPTCGQVtFf63L9s%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjiz176%40pitt.edu%7C7b1494bf977345afb91c08d9e3364ce2%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637790644626261740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=9CE%2BWbvMlsHU6CZDEyjc1O26So8W7TIfkh3rllrE8Iw%3D&reserved=0> or Android<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cjiz176%40pitt.edu%7C7b1494bf977345afb91c08d9e3364ce2%7C9ef9f489e0a04eeb87cc3a526112fd0d%7C1%7C0%7C637790644626261740%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=nx%2Bj01GL%2Bz19FX45R%2BysBT1AcqEgDB2NyE%2B8saQow3Y%3D&reserved=0>.

**Comment by kasnder** [comment]
Thank you for this wonderful tool!!
